//
// Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
//
// On Tue Jan 10 20:04:11 EST 2012
//
// Method conflict info:
// (none)
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkTest(CLK,
	      RST_N);
  input  CLK;
  input  RST_N;

  // ports of submodule wave
  wire [31 : 0] wave$data_get;
  wire wave$EN_data_get,
       wave$EN_token_get,
       wave$RDY_data_get,
       wave$RDY_token_get,
       wave$token_get;

  // submodule wave
  mkConstantWaveform wave(.CLK(CLK),
			  .RST_N(RST_N),
			  .EN_data_get(wave$EN_data_get),
			  .EN_token_get(wave$EN_token_get),
			  .data_get(wave$data_get),
			  .RDY_data_get(wave$RDY_data_get),
			  .token_get(wave$token_get),
			  .RDY_token_get(wave$RDY_token_get));

  // submodule wave
  assign wave$EN_data_get = wave$RDY_token_get && wave$RDY_data_get ;
  assign wave$EN_token_get = wave$RDY_token_get && wave$RDY_data_get ;

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N)
      if (wave$RDY_token_get && wave$RDY_data_get)
	$display("Data: %h, tag: %h", wave$data_get, wave$token_get);
  end
  // synopsys translate_on
endmodule  // mkTest

